# Compiler we will use
CC = gcc

# Compiler options: show warnings, look for headers in "include" folder
CFLAGS = -Wall -Iinclude

# Final program name
TARGET = bin/client

# Object files (compiled versions of .c files)
OBJ = obj/main.o obj/mystrfunctions.o obj/myfilefunctions.o
CC = gcc
CFLAGS = -Wall -Iinclude

SRC = src/main.c
OBJ = obj/main.o

LIB_NAME = libmyutils.a
LIB_DIR = lib
LIB = $(LIB_DIR)/$(LIB_NAME)

TARGET = bin/client_static

# Default target
all: $(TARGET)

# Rule for final executable linking against the static library
$(TARGET): $(OBJ) $(LIB)
	$(CC) $(CFLAGS) -o $@ $(OBJ) -L$(LIB_DIR) -lmyutils

# Rule for static library
$(LIB): obj/mystrfunctions.o obj/myfilefunctions.o
	ar rcs $@ $^

# Compile source to object
obj/%.o: src/%.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf obj/*.o bin/* lib/*.a
# --- Rule 1: Build the final program ---
$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

# --- Rule 2: How to make .o files from .c files ---
obj/%.o: src/%.c
	@mkdir -p obj bin       # make sure folders exist
	$(CC) $(CFLAGS) -c $< -o $@

# --- Rule 3: Clean up ---
clean:
	rm -rf obj/*.o $(TARGET)
